#pragma once

//
// Addresses for game data.
//

constexpr auto TES3_IP_IMAGE = 0x7CEBB0u;
constexpr auto TES3_OP_IMAGE = 0x7A91C4u;

constexpr auto TES3_LOCALVARIABLES_IMAGE = 0x7CEBF8u;
constexpr auto TES3_SCRIPTTARGETREF_IMAGE = 0x7CEBECu;
constexpr auto TES3_SCRIPTTARGETTEMPL_IMAGE = 0x7CEBF4u;
constexpr auto TES3_SECONDOBJECT_IMAGE = 0x7CE6F8u;
constexpr auto TES3_SECONDOBJECT_LENGTH_IMAGE = 0x7CEBB8u;
constexpr auto TES3_VARINDEX_IMAGE = 0x7CEBB4u;

constexpr auto TES3_WORLD_CONTROLLER_IMAGE = 0x7C67DCu;
constexpr auto TES3_GAME_IMAGE = 0x7C6CDCu;
constexpr auto TES3_DATA_HANDLER_IMAGE = 0x7C67E0u;

constexpr auto TES3_DESTINATION_X_IMAGE = 0x7CEA48u;
constexpr auto TES3_DESTINATION_Y_IMAGE = 0x7CEA4Cu;
constexpr auto TES3_DESTINATION_Z_IMAGE = 0x7CEA50u;

constexpr auto TES3_TARGET_ROTX_IMAGE = 0x7CEB08u;
constexpr auto TES3_TARGET_ROTY_IMAGE = 0x7CEB0Cu;
constexpr auto TES3_TARGET_ROTZ_IMAGE = 0x7CEB10u;

constexpr auto TES3_DATA_BUFFER = 0x7CB678u;

//
// Hooking positions.
//

constexpr auto TES3_HOOK_GET_NEXT_INSTRUCTION = 0x50055Bu;
constexpr auto TES3_HOOK_GET_NEXT_INSTRUCTION_SIZE = 0x6u;
constexpr auto TES3_HOOK_GET_NEXT_INSTRUCTION_RETURN = (TES3_HOOK_GET_NEXT_INSTRUCTION + TES3_HOOK_GET_NEXT_INSTRUCTION_SIZE);

constexpr auto TES3_HOOK_RUN_FUNCTION = 0x505831u;
constexpr auto TES3_HOOK_RUN_FUNCTION_SIZE = 0x6u;
constexpr auto TES3_HOOK_RUN_FUNCTION_RETURN = (TES3_HOOK_RUN_FUNCTION + TES3_HOOK_RUN_FUNCTION_SIZE);

constexpr auto TES3_HOOK_PLACE_GETREFERENCE = 0x509992u;
constexpr auto TES3_HOOK_PLACE_GETREFERENCE_SIZE = 0x6u;
constexpr auto TES3_HOOK_PLACE_GETREFERENCE_RETURN = (TES3_HOOK_PLACE_GETREFERENCE + TES3_HOOK_PLACE_GETREFERENCE_SIZE);

//
// Addresses for in-function offsets.
//

constexpr auto TES3_INFUNC_RUN_SCRIPT_OPCODE = 0x505793u;
constexpr auto TES3_INFUNC_SCRIPT_ADD_ITEM = 0x508B54u;
constexpr auto TES3_MALLOC = 0x749471C0u;
constexpr auto TES3_FREE = 0x74947000u;
constexpr auto TES3_REALLOC = 0x749472B0u;

//
// Address of hardcoded data.
//

constexpr auto TES3_DATA_EFFECT_FLAGS = 0x747D88u;
