-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- The mwse string library provides functions for interacting with mwscript string storage.
--- @class mwse.stringlib
mwse.string = {}

--- Creates a string in storage, and returns the numerical key for it.
--- 
--- If the string is already in storage, the previous key will be returned.
--- @param value string No description yet available.
--- @return number result No description yet available.
function mwse.string.create(value) end

--- Returns the numerical key for a given string in storage, or nil if the string isn't in storage.
--- @param id number? *Optional*. No description yet available.
--- @return string result No description yet available.
function mwse.string.get(id) end

