--- @meta

--- 
--- @class bodyPartAssignedEventData
--- @field block boolean If set to `true`, vanilla logic will be suppressed. Returning `false` will set this to `true`.
--- @field claim boolean If set to `true`, any lower-priority event callbacks will be skipped. Returning `false` will set this to `true`.
--- @field bodyPart tes3bodyPart 
--- @field index number *Read-only*. 
--- @field isFirstPerson boolean *Read-only*. 
--- @field manager tes3bodyPartManager *Read-only*. 
--- @field object tes3bodyPart *Read-only*. 
--- @field reference tes3reference *Read-only*. 
