--- @meta

--- 
--- @class bodyPartAssignedEventData
--- @field block boolean If set to `true`, vanilla logic will be suppressed. Returning `false` will set this to `true`.
--- @field claim boolean If set to `true`, any lower-priority event callbacks will be skipped. Returning `false` will set this to `true`.
--- @field manager tes3bodyPartManager 
--- @field bodyPart tes3bodyPart 
--- @field index number 
--- @field reference tes3reference 
--- @field isFirstPerson boolean 
--- @field object tes3bodyPart 
