--- @meta

--- This event fires when a crime is witnessed by an actor.
--- @class crimeWitnessedEventData
--- @field claim boolean If set to `true`, any lower-priority event callbacks will be skipped. Returning `false` will set this to `true`.
--- @field position tes3vector3 *Read-only*. The position that the crime ocurred at.
--- @field realTimestamp number *Read-only*. The timestamp that the crime ocurred at.
--- @field type string *Read-only*. The type of crime that was committed.
--- @field value number *Read-only*. The bounty value of the crime.
--- @field witness tes3reference *Read-only*. The reference that witnessed the crime.
--- @field witnessMobile tes3mobileActor|tes3mobileCreature|tes3mobileNPC|tes3mobilePlayer *Read-only*. The mobile actor of the reference that witnessed the crime.
