-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- This event fires once the game starts creating faders. This event is used to create a new fader using [`tes3fader.new()`](https://mwse.github.io/MWSE/types/tes3fader/#new).
---
--- [Examples available in online documentation](https://mwse.github.io/MWSE/events/fadersCreated).
--- @class fadersCreatedEventData
--- @field claim boolean If set to `true`, any lower-priority event callbacks will be skipped. Returning `false` will set this to `true`.
