-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- This event fires when an inventory filter has been selected for an item.
--- @class filterInventorySelectEventData
--- @field claim boolean If set to `true`, any lower-priority event callbacks will be skipped. Returning `false` will set this to `true`.
--- @field filter boolean Set this value to `true` to make the item appear in the inventory. If this is set to `false` the item won't appear in the inventory.
--- @field item tes3alchemy|tes3apparatus|tes3armor|tes3book|tes3clothing|tes3ingredient|tes3light|tes3lockpick|tes3misc|tes3probe|tes3repairTool|tes3weapon *Read-only*. The item being filtered.
--- @field itemData tes3itemData *Read-only*. The item data for the item being filtered.
--- @field type string *Read-only*. The inventory filter type.
