--- @meta

--- This event fires when a dialogue response is triggered.
--- @class infoResponseEventData
--- @field block boolean If set to `true`, vanilla logic will be suppressed. Returning `false` will set this to `true`.
--- @field claim boolean If set to `true`, any lower-priority event callbacks will be skipped. Returning `false` will set this to `true`.
--- @field command string *Read-only*. The command.
--- @field dialogue tes3dialogue *Read-only*. The dialogue object.
--- @field info tes3dialogueInfo *Read-only*. The dialogue info object.
--- @field reference tes3reference *Read-only*. The reference.
--- @field variables tes3scriptVariables *Read-only*. The script variables.
