--- @meta

--- The key event fires when a key up or key down input is detected. It is preferred that the keyDown and keyUp events are used instead.
---
--- [Examples available in online documentation](https://mwse.github.io/MWSE/events/key).
--- @class keyEventData
--- @field claim boolean If set to `true`, any lower-priority event callbacks will be skipped. Returning `false` will set this to `true`.
--- @field isAltDown number *Read-only*. True if either alt key is held.
--- @field isControlDown number *Read-only*. True if either control key is held.
--- @field isShiftDown number *Read-only*. True if either shift key is held.
--- @field isSuperDown number *Read-only*. True if super (Windows key) is held.
--- @field keyCode number *Read-only*. The scan code of the key that raised the event.
--- @field pressed boolean *Read-only*. True if this is a key down event, false for a key up event.
