--- @meta

--- 
--- @class playGroupEventData
--- @field block boolean If set to `true`, vanilla logic will be suppressed. Returning `false` will set this to `true`.
--- @field claim boolean If set to `true`, any lower-priority event callbacks will be skipped. Returning `false` will set this to `true`.
--- @field animationData tes3animationData 
--- @field flags number 
--- @field group number 
--- @field index number 
--- @field loopCount number 
--- @field reference tes3reference 
