--- @meta

--- 
--- @class soundObjectPlayEventData
--- @field block boolean If set to `true`, vanilla logic will be suppressed. Returning `false` will set this to `true`.
--- @field claim boolean If set to `true`, any lower-priority event callbacks will be skipped. Returning `false` will set this to `true`.
--- @field flags number 
--- @field isNot3D boolean 
--- @field pitch number 
--- @field sound tes3sound 
--- @field volume number 
