return {
    ShortBladeOneHand = 0,
    LongBladeOneHand = 1,
    LongBladeTwoClose = 2,
    BluntOneHand = 3,
    BluntTwoClose = 4,
    BluntTwoWide = 5,
    SpearTwoWide = 6,
    AxeOneHand = 7,
    AxeTwoHand = 8,
    MarksmanBow = 9,
    MarksmanCrossbow = 10,
    MarksmanThrown = 11,
    Arrow = 12,
    Bolt = 13,
}
