return {
	type = "value",
	description = [[Controls the change in speed that new particles generated by a spawn event will have. A value of `0.0` indicates no change in speed, a value of `1.0` indicates a 0 % to 100 % increase in speed, and a value of `-1.0` indicates 0 % to 100 % decrease in speed.]],
	valuetype = "number",
}
