return {
	type = "value",
	description = [[Controls the change in direction that new particles generated by a spawn event will have. A value of `0.0` indicates no change in direction, and a value of `1.0` indicates a 0 % to 100 % change in direction.]],
	valuetype = "number",
}
