local ni = {}

ni.animationKeyType = require("ni.animationKeyType")
ni.animCycleType = require("ni.animCycleType")
ni.animType = require("ni.animType")
ni.billboardMode = require("ni.billboardMode")
ni.dynamicEffectType = require("ni.dynamicEffectType")
ni.eulerRotKeyOrder = require("ni.eulerRotKeyOrder")
ni.gravityForceType = require("ni.gravityForceType")
ni.lightingMode = require("ni.lightingMode")
ni.lookAtControllerAxis = require("ni.lookAtControllerAxis")
ni.particleBombDecayType = require("ni.particleBombDecayType")
ni.particleBombSymmetryType = require("ni.particleBombSymmetryType")
ni.pickCoordinateType = require("ni.pickCoordinateType")
ni.pickIntersectType = require("ni.pickIntersectType")
ni.pickSortType = require("ni.pickSortType")
ni.pickType = require("ni.pickType")
ni.propertyType = require("ni.propertyType")
ni.sourceVertexMode = require("ni.sourceVertexMode")
ni.stencilDrawMode = require("ni.stencilDrawMode")
ni.stencilTestAction = require("ni.stencilTestAction")
ni.stencilTestFunction = require("ni.stencilTestFunction")
ni.textureFormatPrefsAlphaFormat = require("ni.textureFormatPrefsAlphaFormat")
ni.textureFormatPrefsMipFlag = require("ni.textureFormatPrefsMipFlag")
ni.textureFormatPrefsPixelLayout = require("ni.textureFormatPrefsPixelLayout")
ni.texturingPropertyApplyMode = require("ni.texturingPropertyApplyMode")
ni.texturingPropertyClampMode = require("ni.texturingPropertyClampMode")
ni.texturingPropertyFilterMode = require("ni.texturingPropertyFilterMode")
ni.type = require("ni.type")
ni.zBufferPropertyTestFunction = require("ni.zBufferPropertyTestFunction")

return ni
