return {
	["voice"] = {
		["hello"] = 0,
		["idle"] = 1,
		["intruder"] = 2,
		["thief"] = 3,
		["hit"] = 4,
		["attack"] = 5,
		["flee"] = 6,
	},
	["greeting"] = {
		["greeting0"] = 0,
		["greeting1"] = 1,
		["greeting2"] = 2,
		["greeting3"] = 3,
		["greeting4"] = 4,
		["greeting5"] = 5,
		["greeting6"] = 6,
		["greeting7"] = 7,
		["greeting8"] = 8,
		["greeting9"] = 9,
	},
	["service"] = {
		["infoRefusal"] = 0,
		["admireSuccess"] = 1,
		["admireFail"] = 2,
		["initimidateSuccess"] = 3,
		["initimidateFail"] = 4,
		["tauntSuccess"] = 5,
		["tauntFail"] = 6,
		["serviceRefusal"] = 7,
		["bribeSuccess"] = 8,
		["bribeFail"] = 9,
	},
}
