return {
	["shortBladeOneHand"] = 0,
	["longBladeOneHand"] = 1,
	["longBladeTwoClose"] = 2,
	["bluntOneHand"] = 3,
	["bluntTwoClose"] = 4,
	["bluntTwoWide"] = 5,
	["spearTwoWide"] = 6,
	["axeOneHand"] = 7,
	["axeTwoHand"] = 8,
	["marksmanBow"] = 9,
	["marksmanCrossbow"] = 10,
	["marksmanThrown"] = 11,
	["arrow"] = 12,
	["bolt"] = 13,
}
