-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- Allows control of MGE render features.
--- @class mgeRenderFeatures
--- @field atmosphericScattering boolean No description yet available.
--- @field blurReflections boolean No description yet available.
--- @field crosshairAutoHide boolean No description yet available.
--- @field displayMessages boolean No description yet available.
--- @field distantLand boolean No description yet available.
--- @field distantStatics boolean No description yet available.
--- @field distantWater boolean No description yet available.
--- @field dynamicRipples boolean No description yet available.
--- @field exponentialFog boolean No description yet available.
--- @field fpsCounter boolean No description yet available.
--- @field grass boolean No description yet available.
--- @field noMWMGEBlending boolean No description yet available.
--- @field noMWSunglare boolean No description yet available.
--- @field pauseRenderingInMenus boolean No description yet available.
--- @field reflectInterior boolean No description yet available.
--- @field reflectiveWater boolean No description yet available.
--- @field reflectNearStatics boolean No description yet available.
--- @field reflectSky boolean No description yet available.
--- @field shaders boolean No description yet available.
--- @field shadows boolean No description yet available.
--- @field transparencyAA boolean No description yet available.
--- @field updateHDR boolean No description yet available.
mgeRenderFeatures = {}

