-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- A handle to safely operate on ([tes3object](https://mwse.github.io/MWSE/types/tes3object/)).
---
--- [Examples available in online documentation](https://mwse.github.io/MWSE/types/mwseSafeObjectHandle).
--- @class mwseSafeObjectHandle
mwseSafeObjectHandle = {}

--- Returns the object of this handle.
--- @return tes3reference result No description yet available.
function mwseSafeObjectHandle:getObject() end

--- Returns true if the object of this handle is still valid. Objects that are invalid do no longer exist and cannot be used.
function mwseSafeObjectHandle:valid() end

