-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- An object that represents an ambient light. This object is fairly simple, and has no location, direction, or attenuation.
--- @class niAmbientLight : niLight, niDynamicEffect, niAVObject, niObjectNET, niObject
niAmbientLight = {}

