-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- An animation key for bezier curved position.
--- @class niBezPosKey : niPosKey, niAnimationKey
--- @field inTangent tes3vector3 The inbound tangent for the bezier curve.
--- @field outTangent tes3vector3 The outbound tangent for the bezier curve.
niBezPosKey = {}

