-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- An animation key for bezier curved rotation.
--- @class niBezRotKey : niRotKey, niAnimationKey
niBezRotKey = {}

