-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- The NiColorData class provides a shareable wrapper for color animation data. Usually found in niParticleColorModifiers.
--- @class niColorData : niObject
--- @field keyCount integer The number of keys in this niColorData.
--- @field keys niColorKey[] *Read-only*. The keyframe data that this object currently stores.
--- @field keyType integer The type of the keys.
niColorData = {}

