-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- An object that specifies if the collision system is enabled.
--- @class niCollisionSwitch : niNode, niAVObject, niObjectNET, niObject
--- @field collisionActive boolean The enabled state of collision on the collision switch.
niCollisionSwitch = {}

