-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- An attachment to NiObjectNETs that allows the storing of arbitrary data onto the given object.
--- @class niExtraData : niObject
--- @field genericData number[] *Read-only*. Generic data held in the extra data. This is not used if a subtype of extra data is used.
--- @field next niStringExtraData|niTES3ExtraData|niTextKeyExtraData The next extra data available on the object.
niExtraData = {}

