-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- A simple animation key, that holds an arbitrary floating point value.
--- @class niFloatKey : niAnimationKey
--- @field value number The arbitrary value of the NiFloatKey.
niFloatKey = {}

