-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- A rendering property that controls the appearance of fogging.
--- @class niFogProperty : niProperty, niObjectNET, niObject
--- @field color niColor *Read-only*. The fog color.
--- @field density number The fog density.
niFogProperty = {}

