-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- A rendering property that controls the appearance of fogging, also known as haze.
--- @class niFogProperty : niProperty, niObjectNET, niObject
--- @field color integer[] *Read-only*. The RGBA fog color value in range [0, 255].
--- @field density number The fog density in normalized units [0.0, 1.0]. If set to 1.0, then the fogging begins at the near plane. If set to a value of 0.5, then fogging begins halfway between the near and far planes in world space.
niFogProperty = {}

