-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- A rendering property that controls the surface properties of objects affected by the property. These surface properties include translucency, ambient reflective color, diffuse reflective color, emissive color intensity, and specular color.
--- @class niMaterialProperty : niProperty, niObjectNET, niObject
--- @field alpha number The alpha value of the material. Value should be in [0.0, 1.0] range. Setting this value also marks the material as changed, so that renderer knows that it needs to update its copies of the material settings.
--- @field ambient niColor The ambient material color. Setting this value also marks the material as changed, so that renderer knows that it needs to update its copies of the material settings.
--- @field diffuse niColor The diffuse material color. Setting this value also marks the material as changed, so that renderer knows that it needs to update its copies of the material settings.
--- @field emissive niColor The emissive material color. Setting this value also marks the material as changed, so that renderer knows that it needs to update its copies of the material settings.
--- @field shininess number The shine of the material. Value should be >= 0. Higher values tend to make the material appear to have a more mirror-like finish. Setting this value also marks the material as changed, so that renderer knows that it needs to update its copies of the material settings.
--- @field specular niColor The specular material color. Setting this value also marks the material as changed, so that renderer knows that it needs to update its copies of the material settings.
niMaterialProperty = {}

--- This marks the material as changed, so that the renderer knows that it needs to update the copies of the material settings.
function niMaterialProperty:incrementRevisionId() end

