-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- This modifer applies acceleration to particles in the parent niParticleSystemController.
--- @class niParticleBomb : niParticleModifier, niObject
--- @field decay number The niParticleBomb modifers with decayType linear and exponential have their strength attenuated with distance. No attenuation occurs within the `.decay` distance of the niParticelBomb's position.
--- @field decayType integer Controls how the force applied attenuates with distance.
--- @field deltaV number The acceleration applied to the particles.
--- @field direction tes3vector3 The direction of applied acceleration used for cylindrical and planar particle bombs.
--- @field duration number Controls how long this modifer affects the particles.
--- @field position tes3vector3 
--- @field start number The time at which this modifier start affecting the particles.
--- @field symmetryType integer Controls how this modifer affects the particles. Spherical modifer operates around the point defined by `.position` property. Cylindrical modifer applied the force parallel to the `.direction` vector, centered at `position` property. Planar modifers operate perpendicular to the `.direction` vector.
niParticleBomb = {}

