-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- This modifer alters the size and fading of the particles. The growing starts once a particle is first created, so that when a particle appears it will grow from nothing to its full size. Particles fade out of existance when they die, changing their size from full to nothing. If the two effects overlap, the particle will be smaller (to extinguish dying particles).
--- @class niParticleGrowFade : niParticleModifier, niObject
--- @field fade number The time over which the particles grow smaller, and at the end completely disappear.
--- @field grow number The time over which the particles grow larger.
niParticleGrowFade = {}

