-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- An object that represents a RGB color with alpha channel support. Unlike other color values, this is compressed into 4 bytes. Values are not from 0 to 1, but from 0 to 255.
--- @class niPackedColor
--- @field a integer The alpha value of the color.
--- @field alpha integer The alpha value of the color.
--- @field b integer The blue value of the color.
--- @field blue integer Alias for the blue value of the color.
--- @field g integer The green value of the color.
--- @field green integer Alias for the green value of the color.
--- @field r integer The red value of the color.
--- @field red integer Alias for the red value of the color.
niPackedColor = {}

--- Creates a new niPackedColor object.
--- @param r integer? *Default*: `0`. The red value for the color.
--- @param g integer? *Default*: `0`. The green value for the color.
--- @param b integer? *Default*: `0`. The blue value for the color.
--- @param a integer? *Default*: `0`. The alpha value for the color.
--- @return niPackedColor color No description yet available.
function niPackedColor.new(r, g, b, a) end

