-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- Abstract base class for particle system modifiers.
--- @class niParticleModifier : niObject
--- @field controller niParticleSystemController Access to the generic time controller for particle systems.
--- @field next niParticleModifier Access to the next attached modifier.
niParticleModifier = {}

