-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- An object that represent collections of large numbers of small point-like objects, designed for dynamic effects like fountains, waterfalls, snow, explosions, etc.
--- @class niParticles : niTriBasedGeometry, niGeometry, niAVObject, niObjectNET, niObject
--- @field data niParticlesData|niRotatingParticlesData The niParticlesData of the object. Manipulation should not be done directly. Instead, consider copying the data and assigning it to this shape.
niParticles = {}

