-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- A nested class of NiPick that stores the results of previous picking operations for use by the game engine.
--- @class niPickRecord
--- @field color niPackedColor The vertex color at the point of intersection. The color is valid only when `returnColor = true`.
--- @field distance number The distance of the triangle intersection from the ray origin.
--- @field intersection tes3vector3 The intersection point on the triangle.
--- @field normal tes3vector3 The normal vector at the point of intersection. The normal is valid only when `returnNormal = true` in the parent niPick object.
--- @field object niAmbientLight|niBillboardNode|niCamera|niCollisionSwitch|niDirectionalLight|niNode|niParticles|niPointLight|niRotatingParticles|niSpotLight|niSwitchNode|niTextureEffect|niTriShape *Read-only*. The object of the record.
--- @field parent niAmbientLight|niBillboardNode|niCamera|niCollisionSwitch|niDirectionalLight|niNode|niParticles|niPointLight|niRotatingParticles|niSpotLight|niSwitchNode|niTextureEffect|niTriShape *Read-only*. The parent of the record.
--- @field reference tes3reference *Read-only*. Quick access to the associated object's reference.
--- @field texture tes3vector2 The texture coordinates at the point of intersection. The coordinates are valid only when `returnTexture = true` in the parent niPick object.
--- @field triangleIndex integer The index of the intersected triangle.
--- @field vertexIndex integer[] An array containing the 3 indices of the vertices that form the triangle at the intersection point.
niPickRecord = {}

