-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- This modifier makes particles bounce off of a rectangle.
--- @class niPlanarCollider : niParticleCollider, niParticleModifier, niObject
--- @field height number The plane size along the y axis.
--- @field planeEquation tes3vector4 The coefficients in the point-normal form equation of the plane.
--- @field position tes3vector3 The center point of the collider.
--- @field width number The plane size along the x axis.
--- @field xAxis tes3vector3 The x axis, lying in the plane of the collider.
--- @field yAxis tes3vector3 The y axis, lying in the plane of the collider.
niPlanarCollider = {}

