-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- Represents a point light source in a scene. Point lights have a specific location in space and a distance attenuation function. Point lights project light in all directions from their position. They can be moved by changing the translation of the light.
--- @class niPointLight : niLight, niDynamicEffect, niAVObject, niObjectNET, niObject
--- @field constantAttenuation number The constant attenuation factor.
--- @field linearAttenuation number The linear attenuation factor.
--- @field quadraticAttenuation number The quadratic attenuation factor.
niPointLight = {}

--- Creates a new niPointLight. Sets the light's constant attenuation to 0, linear attenuation to 1 and quadratic attenuation to 0.
--- @return niPointLight|niSpotLight light No description yet available.
function niPointLight.new() end

--- Sets the light attenuation values for the given radius. Respects the values in the `Morrowind.ini` file.
--- @param radius integer No description yet available.
function niPointLight:setAttenuationForRadius(radius) end

--- Sets both the light's influence radius, and its lighting attenuation to match the radius.
--- @param radius integer No description yet available.
function niPointLight:setRadius(radius) end

