-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- An animation key that holds a position value.
--- @class niPosKey : niAnimationKey
--- @field value tes3vector3 The position value of the animation key.
niPosKey = {}

