-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- A linked list of properties.
--- @class niPropertyLinkedList
--- @field data niAlphaProperty|niFogProperty|niMaterialProperty|niStencilProperty|niTexturingProperty|niVertexColorProperty The current property in the linked list.
--- @field next niPropertyLinkedList The next property in the linked list.
niPropertyLinkedList = {}

