-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- A base class representing all rendering properties.
--- @class niProperty : niObjectNET, niObject
--- @field type niPropertyType The unique class identifier number of the given rendering property.
niProperty = {}

