-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- Runtime type information for NetImmerse structures.
--- @class niRTTI
--- @field name string The human readable name for the type.
--- @field parent niRTTI The runtime type information that this type derives from.
niRTTI = {}

