-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- An instance of `niSkinDataBoneDataVertexWeight` exists for every vertex that is influenced by a particular bone. This container stores the weight coefficients used for each vertex when deforming skinned objects with this bone.
--- @class niSkinDataBoneDataVertexWeight
--- @field index integer The index of the vertex in the skinned object's array of vertices.
--- @field weight number The weight of the bone's influence on the vertex. The sum of the weights for all the bones that influence a particular vertex must be 1.0.
niSkinDataBoneDataVertexWeight = {}

