-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- A container for skinning data, optimized for hardware skinning. The mesh is partitioned in submeshes such that each vertex of a submesh is influenced only by a limited and fixed number of bones (in Morrowind up to 4 bones can deform a single vertex).
--- @class niSkinPartition : niObject
--- @field partitions niSkinPartitionPartition[]|nil *Read-only*. Access to the array of actual skin partitions.
niSkinPartition = {}

