-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- Contains instance-dependent skinning data for a `NiTriShape` object.
--- @class niSkinInstance : niObject
--- @field bones niAmbientLight[]|niBillboardNode[]|niCamera[]|niCollisionSwitch[]|niDirectionalLight[]|niNode[]|niParticles[]|niPointLight[]|niRotatingParticles[]|niSpotLight[]|niSwitchNode[]|niTextureEffect[]|niTriShape[] *Read-only*. The bone influences for this skin instance.
--- @field data niSkinData The skinning data. May be shared by multiple skin instances.
--- @field root niBillboardNode|niCollisionSwitch|niNode|niSwitchNode The skeleton root (parent of the root bone).
niSkinInstance = {}

