-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- Contains instance-dependent skinning data for a `NiTriShape` object.
--- @class niSkinInstance : niObject
--- @field bones niAmbientLight[]|niBillboardNode[]|niCamera[]|niCollisionSwitch[]|niDirectionalLight[]|niDynamicEffect[]|niGeometry[]|niLight[]|niNode[]|niPointLight[]|niSpotLight[]|niSwitchNode[]|niTriBasedGeometry[]|niTriShape[] The bone influences for this skin instance.
--- @field data niSkinData The skinning data. May be shared by multiple skin instances.
--- @field root niAmbientLight|niBillboardNode|niCamera|niCollisionSwitch|niDirectionalLight|niDynamicEffect|niGeometry|niLight|niNode|niPointLight|niSpotLight|niSwitchNode|niTriBasedGeometry|niTriShape The skeleton root (parent of the root bone).
niSkinInstance = {}

