-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- Skinning data for a submesh, optimized for hardware skinning.
--- @class niSkinPartitionPartition
--- @field bones integer[] *Read-only*. The list of bone indices (that influence this partition) from the bones array in the parent `niSkinInstance` node.
--- @field bonesPerVertex integer 
--- @field stripLengths integer[] *Read-only*. 
--- @field triangles niTriangle[] *Read-only*. The triangles that form this submesh.
--- @field vertices integer[] *Read-only*. Maps the weight/influence list in this submesh to the vertices in the shape being skinned.
niSkinPartitionPartition = {}

