-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- Contains skinning data that may be shared by multiple `NiSkinInstance` objects.
--- @class niSkinData : niObject
niSkinData = {}

