-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- Contains skinning data that may be shared by multiple `NiSkinInstance` objects.
--- @class niSkinData : niObject
--- @field boneData niSkinDataBoneData[] *Read-only*. An array of objects containing one entry for each bone that influences vertices in the skinned mesh. The order of the entries in the `boneData` array corresponds to the order of the bones in the bone array in the `niSkinInstance` objects that point to this `niSkinData`. Each object in this array contains all the data needed to deform vertices by a single bone.
--- @field partition niSkinPartition|nil Access to the container with the skinning data optimized for hardware skinning. If the `niSkinData` object has not been partitioned, this property is `nil`.
--- @field rotation tes3matrix33 Defines the rotation of the root bone in the bind pose from the parent node of the root bone to the coordinate system of the skinned object.
--- @field scale number Defines the scale of the root bone in the bind pose from the parent node of the root bone to the coordinate system of the skinned object.
--- @field translation tes3vector3 Defines the translation of the root bone in the bind pose from the parent node of the root bone to the coordinate system of the skinned object.
niSkinData = {}

