-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- This modifier makes particles bounce off of a sphere.
--- @class niSphericalCollider : niParticleCollider, niParticleModifier, niObject
--- @field position tes3vector3 The center of the deflecting sphere.
--- @field radius number The radius of the used spherical deflector.
niSphericalCollider = {}

