-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- A simple extra data that contains a string.
--- @class niStringExtraData : niExtraData, niObject
--- @field string string The string kept on the niStringExtraData.
niStringExtraData = {}

--- Creates an niStringExtraData.
--- @param string string The initial value for the extra data to store.
--- @return niStringExtraData extraData No description yet available.
function niStringExtraData.new(string) end

