-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- Represents groups of multiple scene graph subtrees, only one of which is visible at any given time. They are useful for showing different states of a model depending on engine / lua logic. If you detach the active subtree, the switch node will set the active subtree to none, or to an index of -1.
--- @class niSwitchNode : niNode, niAVObject, niObjectNET, niObject
--- @field switchIndex integer The value of the active child index. This index represents the index of the active child in the `children` array of the niSwitchNode. If this index is -1, then no child is active.
niSwitchNode = {}

--- Gets the active child node, or returns nil if the switch index is -1.
--- @return niAmbientLight|niBillboardNode|niCamera|niCollisionSwitch|niDirectionalLight|niNode|niParticles|niPointLight|niRotatingParticles|niSpotLight|niSwitchNode|niTextureEffect|niTriShape result No description yet available.
function niSwitchNode:getActiveChild() end

