-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- An animation key for tension-, continuity-, and bias-derived rotating.
--- @class niTCBRotKey : niRotKey, niAnimationKey
--- @field bias number The bias value for the TCB rotation animation key.
--- @field continuity number The continuity value for the TCB rotation animation key.
--- @field tension number The tension value for the TCB rotation animation key.
niTCBRotKey = {}

