-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- A class used to store an array of niTextKey objects. These objects are a list of textual notes and at which time they take effect. These keys are used for designating the start and stop of animations and the triggering of sounds.
--- @class niTextKeyExtraData : niExtraData, niObject
--- @field keys niTextKey[] *Read-only*. The access to the text key objects stored on this niTextKeyExtraData.
niTextKeyExtraData = {}

