-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- A class used to represent text notes that have an associated time value. They are used for designating the start and stop of animations and the triggering of sounds.
--- @class niTextKey
--- @field text string 
--- @field time number 
niTextKey = {}

