-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- Represents all texture objects that are created from a file or a block of in-memory pixel data.
--- @class niTexture : niObjectNET, niObject
--- @field formatPrefs niFormatPrefs The `NiFormatPrefs` of the texture.
--- @field height number *Read-only*. The height of the texture.
--- @field width number *Read-only*. The width of the texture.
niTexture = {}

