-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- Represents an effect that uses projected textures such as projected lights (gobos) and shadows, environment maps, and fog maps. Should be in both the children list and effects list of the niTriShape object.
--- 
--- For Morrowind: the bump map can be used to bump the environment map (note that the bump map is ignored if no niTextureEffect object is present).
--- @class niTextureEffect : niDynamicEffect, niAVObject, niObjectNET, niObject
--- @field sourceTexture niSourceTexture The texture used for the texture effect.
niTextureEffect = {}

--- Creates a new texture effect object.
--- @return niTextureEffect effect No description yet available.
function niTextureEffect.new() end

