-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- Contains the geometry data for an `NiTriShape` object.
--- @class niTriangle
--- @field verticies number[] The access to the three indices of the verticies that make up this triangle (0-indexed).
niTriangle = {}

