-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- Contains the actual geometry data for a `NiTriBasedGeometry` object.
--- @class niTriBasedGeometryData : niGeometryData, niObject
--- @field activeTriangleCount number The active triangle count of the object.
--- @field triangleCount number *Read-only*. The triangle count of the object.
niTriBasedGeometryData = {}

