-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- A rendering property that allows the application to set the test and write modes of the renderer's Z-buffer and to set the comparison function used for the Z-buffer test.
--- @class niZBufferProperty : niProperty, niObjectNET, niObject
--- @field testFunction integer The Z-buffer test function.
--- 
--- Note that "less than" means closer to the camera and "greater than" means further from the camera, regardless of the low-level hardware representation of Z values.
--- Value | Mode                | Description
--- ----- | ------------------- | -----------------
--- 0     | ZCOMP_ALWAYS        | Test will allways succeed. The Z Buffer value is ignored.
--- 1	  | ZCOMP_LESS          | The test will only succeed if the pixel is nearer than the previous pixel.
--- 2     | ZCOMP_EQUAL         | Test will only succeed if the Z value of the pixel to be drawn is equal to the value of the previous drawn pixel.
--- 3     | ZCOMP_LESS_EQUAL    | Test will succeed if the Z value of the pixel to be drawn is smaller than or equal to the value in the Z Buffer.
--- 4     | ZCOMP_GREATER       | Opposite of TEST_LESS
--- 5     | ZCOMP_NOT_EQUAL     | Test will succeed if the Z value of the pixel to be drawn is NOT equal to the value of the previously drawn pixel.
--- 6     | ZCOMP_GREATER_EQUAL | Opposite of TEST_LESS_EQUAL.
--- 7     | ZCOMP_NEVER         | Test will allways return false. Nothing is drawn at all.
niZBufferProperty = {}

--- Creates a new niVertexColorProperty with `lighting` set to `LIGHT_MODE_EMI_AMB_DIF` and `source` set to `VERT_MODE_SRC_IGNORE`.
--- @return niVertexColorProperty property No description yet available.
function niZBufferProperty.new() end

