-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- A rendering property that allows the application to set the test and write modes of the renderer's Z-buffer and to set the comparison function used for the Z-buffer test.
--- @class niZBufferProperty : niProperty, niObjectNET, niObject
--- @field testFunction integer The Z-buffer test function used. Maps to values in [`ni.zBufferPropertyTestFunction`](https://mwse.github.io/MWSE/references/ni/z-buffer-property-test-functions/) table.
niZBufferProperty = {}

--- Creates a new niZBufferProperty with `testFunction` set to `ni.zBufferPropertyTestFunction.lessEqual`.
--- @return niZBufferProperty property No description yet available.
function niZBufferProperty.new() end

