-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- A pair of vectors marking a bounding box.
--- @class tes3boundingBox
--- @field max tes3vector3 The maximum bound of the box.
--- @field min tes3vector3 The minimum bound of the box.
tes3boundingBox = {}

--- Creates a copy of the bounding box.
--- @return tes3boundingBox result No description yet available.
function tes3boundingBox:copy() end

--- Returns a table containing the 8 vertices comprising this bounding box.
--- @return tes3vector3[] result No description yet available.
function tes3boundingBox:vertices() end

