-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- A game structure which holds all active projectiles.
--- @class tes3projectileManager
--- @field projectiles tes3iterator *Read-only*. A list of all currently active projectiles ([tes3mobileProjectile](https://mwse.github.io/MWSE/types/tes3mobileProjectile/)).
tes3projectileManager = {}

