-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- A complex container that holds a relationship between an item, and zero or more associated item datas.
--- 
--- Item stack represents all copies of an item with the same id. Some of those may have itemData and some may not. E.g. you might have two lockpicks and one of them has fewer uses remaining.
--- So `itemStack.variables` is a list of different itemData for each thing in the stack, not a single itemData.
---
--- [Examples available in online documentation](https://mwse.github.io/MWSE/types/tes3itemStack).
--- @class tes3itemStack
--- @field count integer The total number of items in the stack.
--- @field object tes3alchemy|tes3apparatus|tes3armor|tes3book|tes3clothing|tes3ingredient|tes3light|tes3lockpick|tes3misc|tes3probe|tes3repairTool|tes3weapon *Read-only*. The core game object that the stack represents.
--- @field variables tes3itemData[] A collection of variables that are associated with the stack's object, or nil if there aren't any.
tes3itemStack = {}

