-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- A game object which contains information that map actor sounds to animations.
--- @class tes3animationDataSoundGenKey
--- @field pitch number The pitch of the sound.
--- @field sound tes3sound The sound played at this sound generator key.
--- @field startFrame number The starting frame of animation at which the sound plays.
--- @field startTime number 
--- @field volume number The sound's volume.
tes3animationDataSoundGenKey = {}

