-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- Almost anything that can be represented in the Construction Set is based on this structure.
--- @class tes3physicalObject : tes3object, tes3baseObject
--- @field boundingBox tes3boundingBox The bounding box for the object.
--- @field stolenList tes3activator[]|tes3alchemy[]|tes3apparatus[]|tes3armor[]|tes3birthsign[]|tes3bodyPart[]|tes3book[]|tes3cell[]|tes3class[]|tes3clothing[]|tes3container[]|tes3containerInstance[]|tes3creature[]|tes3creatureInstance[]|tes3dialogue[]|tes3dialogueInfo[]|tes3door[]|tes3enchantment[]|tes3faction[]|tes3gameSetting[]|tes3globalVariable[]|tes3ingredient[]|tes3leveledCreature[]|tes3leveledItem[]|tes3light[]|tes3lockpick[]|tes3magicSourceInstance[]|tes3misc[]|tes3npc[]|tes3npcInstance[]|tes3probe[]|tes3quest[]|tes3race[]|tes3reference[]|tes3region[]|tes3repairTool[]|tes3script[]|tes3skill[]|tes3sound[]|tes3soundGenerator[]|tes3spell[]|tes3startScript[]|tes3static[]|tes3weapon[] A list of actors that the object has been stolen from.
tes3physicalObject = {}

