-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- A game object which contains niSequence objects for each animation body section.
--- @class tes3animationDataSequenceGroup
--- @field leftArm niSequence The niSequence object for the actor's left arm.
--- @field lower niSequence The niSequence object for the actor's legs.
--- @field upper niSequence The niSequence object for the actor's upper body.
tes3animationDataSequenceGroup = {}

