-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- A UI widget is a special interface to an element that offers functionality in a more friendly way.
--- 
--- Some core widget interfaces offered by MWSE include:
--- * [tes3uiButton](https://mwse.github.io/MWSE/types/tes3uiButton)
--- * [tes3uiFillBar](https://mwse.github.io/MWSE/types/tes3uiFillBar)
--- * [tes3uiParagraphInput](https://mwse.github.io/MWSE/types/tes3uiParagraphInput)
--- * [tes3uiScrollPane](https://mwse.github.io/MWSE/types/tes3uiScrollPane)
--- * [tes3uiSlider](https://mwse.github.io/MWSE/types/tes3uiSlider)
--- * [tes3uiTextInput](https://mwse.github.io/MWSE/types/tes3uiTextInput)
--- * [tes3uiTextSelect](https://mwse.github.io/MWSE/types/tes3uiTextSelect)
--- @class tes3uiWidget
--- @field element tes3uiElement Access back to the element this widget interface is for.
tes3uiWidget = {}

