-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- The manager responsible for mobile objects and collision.
--- @class tes3mobManager
--- @field processManager tes3processManager *Read-only*. Access to the process manager.
--- @field projectileManager tes3projectileManager *Read-only*. Access to the projectile manager.
tes3mobManager = {}

