--- @meta

--- A core magic effect definition.
--- @class tes3magicEffect
--- @field allowEnchanting boolean Access to the flag that determines if this effect can be used in enchanting.
--- @field allowSpellmaking boolean Access to the flag that determines if this effect can be used with spellmaking.
--- @field appliesOnce boolean Access to the base flag that determines if this effect can be used in enchanting.
--- @field areaSoundEffect string The sound path to the sound effect to use for area of effect impacts.
--- @field baseFlags number No description yet available.
--- @field baseMagickaCost number The base magicka cost to use in calculations.
--- @field boltSoundEffects string The sound path to the sound effect to use for target projectiles.
--- @field canCastSelf boolean Access to the base flag that determines if this effect can be used with a range of self.
--- @field canCastTarget boolean Access to the base flag that determines if this effect can be used with a range of target.
--- @field canCastTouch boolean Access to the base flag that determines if this effect can be used with a range of touch.
--- @field casterLinked boolean Access to the base flag.
--- @field castSoundEffect string The sound path to the sound effect to use when casting.
--- @field flags number Raw access to the numerical representation of flags. Typically shouldn't be used.
--- @field hasContinuousVFX boolean Access to the base flag that determines if this effect's VFX continuously plays.
--- @field hasNoDuration boolean Access to the base flag that determines if this effect doesn't use a duration.
--- @field hasNoMagnitude boolean Access to the base flag that determines if this effect doesn't make use of its magnitude.
--- @field hitSoundEffect string The sound path to the sound effect to use when the effect hits a target.
--- @field icon string The sound path to the icon to use for the effect.
--- @field id number The numerical id for the effect.
--- @field illegalDaedra boolean Access to the base flag that determines if this effect summons an illegal daedra. This flag isn't used.
--- @field isHarmful boolean Access to the base flag that determines if this effect is counted as a hostile action.
--- @field lightingBlue number The amount of blue lighting to use when lighting projectiles.
--- @field lightingGreen number The amount of green lighting to use when lighting projectiles.
--- @field lightingRed number The amount of red lighting to use when lighting projectiles.
--- @field nonRecastable boolean Access to the base flag that determines if this effect can be refreshed by recasting.
--- @field particleTexture boolean The path to use for the particle effect texture.
--- @field school number The school that the effect is associated with.
--- @field size number No description yet available.
--- @field sizeCap number No description yet available.
--- @field skill number The skill for the associated school that the effect is associated with.
--- @field speed number No description yet available.
--- @field targetsAttributes boolean Access to the base flag that determines if this effect makes use of attributes.
--- @field targetsSkills boolean Access to the base flag that determines if this effect makes use of skills.
--- @field unreflectable boolean Access to the base flag that determines if this effect can't be reflected.
--- @field usesNegativeLighting boolean Access to the base flag that determines if this effect provides negative lighting.
tes3magicEffect = {}

