-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- A representation of a quest, with associated dialogue and info.
--- @class tes3quest : tes3baseObject
--- @field dialogue tes3iterator *Read-only*. A collection of dialogues associated with the quest.
--- @field info tes3iterator *Read-only*. A collection of dialogue info associated with the quest.
tes3quest = {}

