-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- An AI Wander package idle node game object. Contains information on the chance that the actor will wander at that idle node.
--- @class tes3aiPackageWanderIdleNode
--- @field chance number A chance that the actor will wander at this idle node.
--- @field index number The index of this idle node.
tes3aiPackageWanderIdleNode = {}

