-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- A navigation graph used for pathfinding through cells. Composed of nodes (waypoints) connected by navigable edges. Pathgrid data is only available when the `isLoaded` property is true.
--- @class tes3pathGrid : tes3baseObject
--- @field granularity number *Read-only*. Unknown purpose.
--- @field isLoaded boolean *Read-only*. If the game has loaded the path grid data.
--- @field nodeCount number *Read-only*. The total number of nodes.
--- @field nodes tes3pathGridNode[] *Read-only*. A list of all path nodes in the grid. Note that for some cells, not all nodes are placed on the ground.
--- @field parentCell tes3cell *Read-only*. The cell that the pathgrid belongs to.
tes3pathGrid = {}

