-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- This class is a template array used for some parts of the API. They are mostly invisible to the user since they can be looped over the same as over standard array-style tables.
--- @class tes3tarray
tes3tarray = {}

