-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- A structure that contains region sound information.
--- @class tes3regionSound
--- @field chance number The chance the region sound will be used. Must be an integer between 0 - 100.
--- @field sound tes3sound The access to object's associated sound.
tes3regionSound = {}

