-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- This table defines an option available for a tes3uiCycleButton. This must at minimum contain `text`, though it can also contain a `value` or any arbitrary other data.
--- @class tes3uiCycleButtonOption
--- @field text string The text to use when this option is active.
--- @field value any An optional value associated with this option.
tes3uiCycleButtonOption = {}

