-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- A structure containing properties specific to paragraph inputs.
--- @class tes3uiParagraphInput : tes3uiWidget
--- @field lengthLimit number? *Default*: `1023`. The character limit. Inputting additional characters will not be possible if this limit has been reached.
tes3uiParagraphInput = {}

