-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- Data for a texture used by a landscape object.
--- @class tes3landTexture : tes3baseObject
--- @field filename string *Read-only*. The texture filename.
--- @field id string *Read-only*. The id string.
--- @field index number *Read-only*. The 0-based index number, as used in landscape objects.
--- @field texture niSourceTexture *Read-only*. The texture object. Only available when the texture is loaded in an active cell.
tes3landTexture = {}

