-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- An object representing an active splash, such as a blood particle.
--- @class tes3splashControllerActiveSplash
--- @field age number The splash's current age, measured in seconds.
--- @field maxAge number The splash's maximum age, measured in seconds.
--- @field node niBillboardNode|niCollisionSwitch|niNode|niSwitchNode *Read-only*. The splash's node.
tes3splashControllerActiveSplash = {}

