-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- An AI Follow package game object. Sets an actor to follow another actor at a certain distance.
--- @class tes3aiPackageFollow : tes3aiPackage
--- @field destination tes3vector3 This is the position at which the following actor will stop following their target.
--- @field followDistance number The distance between the follower and their target in the in-game units.
--- @field targetActor tes3mobileActor|tes3mobileCreature|tes3mobileNPC|tes3mobilePlayer The actor this follow AI package is set to follow.
tes3aiPackageFollow = {}

