-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- An AI Escort package game object. Sets an actor to follow another actor to a destination.
--- @class tes3aiPackageEscort : tes3aiPackage
--- @field destination tes3vector3 The coordinates for destination of this AI travel package.
--- @field targetActor tes3container|tes3containerInstance|tes3creature|tes3creatureInstance|tes3npc|tes3npcInstance The actor this AI escort package is set to follow.
tes3aiPackageEscort = {}

