-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- A structure that contains weather information for the cloudy weather type.
--- @class tes3weatherCloudy : tes3weather
tes3weatherCloudy = {}

