-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- A collection that can be iterated over. Contains items in a simple linked list, and stores its head/tail.
--- @class tes3equipmentStackIterator
--- @field count integer Returns the amount of items in the iterator.
--- @field current tes3equipmentStackIteratorNode A reference for the currently iterated node. This is used by the core game engine, but should not be accessed from lua.
--- @field head tes3equipmentStackIteratorNode The first node in the collection.
--- @field tail tes3equipmentStackIteratorNode The last node in the collection.
tes3equipmentStackIterator = {}

