-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- A node within a path grid.
--- @class tes3pathGridNode
--- @field position tes3vector3 *Read-only*. The world position of the node.
tes3pathGridNode = {}

