--- @meta

--- A core magic effect definition.
--- @class tes3magicEffect
--- @field allowEnchanting boolean Access to the flag that determines if this effect can be used in enchanting.
--- @field allowSpellmaking boolean Access to the flag that determines if this effect can be used with spellmaking.
--- @field appliesOnce boolean Access to the base flag that determines if this effect is applied only once.
--- @field areaSoundEffect tes3sound The sound effect that plays on area of effect impacts. Can be set to ``nil`` to use the default sound effect for the magic school.
--- @field areaVisualEffect tes3activator|tes3alchemy|tes3apparatus|tes3armor|tes3bodyPart|tes3book|tes3clothing|tes3container|tes3containerInstance|tes3creature|tes3creatureInstance|tes3door|tes3ingredient|tes3leveledCreature|tes3leveledItem|tes3light|tes3lockpick|tes3misc|tes3npc|tes3npcInstance|tes3probe|tes3repairTool|tes3static|tes3weapon The visual played when a spell with this effect, with area of effect hits something.
--- @field baseFlags number No description yet available.
--- @field baseMagickaCost number The base magicka cost to use in calculations.
--- @field bigIcon string The path to the large icon to use for the effect. This is derived from the base icon path.
--- @field boltSoundEffect tes3sound The sound effect that plays for magic projectiles. Can be set to ``nil`` to use the default sound effect for the magic school.
--- @field boltVisualEffect tes3activator|tes3alchemy|tes3apparatus|tes3armor|tes3bodyPart|tes3book|tes3clothing|tes3container|tes3containerInstance|tes3creature|tes3creatureInstance|tes3door|tes3ingredient|tes3leveledCreature|tes3leveledItem|tes3light|tes3lockpick|tes3misc|tes3npc|tes3npcInstance|tes3probe|tes3repairTool|tes3static|tes3weapon The visual played when a spell with this effect is in flight.
--- @field canCastSelf boolean Access to the base flag that determines if this effect can be used with a range of self.
--- @field canCastTarget boolean Access to the base flag that determines if this effect can be used with a range of target.
--- @field canCastTouch boolean Access to the base flag that determines if this effect can be used with a range of touch.
--- @field casterLinked boolean Access to the base flag.
--- @field castSoundEffect tes3sound The sound effect that plays when casting. Can be set to ``nil`` to use the default sound effect for the magic school.
--- @field castVisualEffect tes3activator|tes3alchemy|tes3apparatus|tes3armor|tes3bodyPart|tes3book|tes3clothing|tes3container|tes3containerInstance|tes3creature|tes3creatureInstance|tes3door|tes3ingredient|tes3leveledCreature|tes3leveledItem|tes3light|tes3lockpick|tes3misc|tes3npc|tes3npcInstance|tes3probe|tes3repairTool|tes3static|tes3weapon The visual played when a spell with this effect is cast.
--- @field description string Player-facing description of the effect.
--- @field flags number Raw access to the numerical representation of flags. Typically shouldn't be used.
--- @field hasContinuousVFX boolean Access to the base flag that determines if this effect's VFX continuously plays.
--- @field hasNoDuration boolean Access to the base flag that determines if this effect doesn't use a duration.
--- @field hasNoMagnitude boolean Access to the base flag that determines if this effect doesn't make use of its magnitude.
--- @field hitSoundEffect tes3sound The sound effect that plays when the effect hits a target. Can be set to ``nil`` to use the default sound effect for the magic school.
--- @field hitVisualEffect tes3activator|tes3alchemy|tes3apparatus|tes3armor|tes3bodyPart|tes3book|tes3clothing|tes3container|tes3containerInstance|tes3creature|tes3creatureInstance|tes3door|tes3ingredient|tes3leveledCreature|tes3leveledItem|tes3light|tes3lockpick|tes3misc|tes3npc|tes3npcInstance|tes3probe|tes3repairTool|tes3static|tes3weapon The visual played when a spell with this effect hits something.
--- @field icon string The path to the icon to use for the effect.
--- @field id number *Read-only*. The unique identifier for the magic effect. Maps to values in [`tes3.effect`](https://mwse.github.io/MWSE/references/magic-effects/). Values not defined in `tes3.effect` are also possible for magic effects added by mods that don't use [`tes3.claimSpellEffectId()`](https://mwse.github.io/MWSE/apis/tes3/#tes3claimspelleffectid) to register their id.
--- @field illegalDaedra boolean Access to the base flag that determines if this effect summons an illegal daedra. This flag isn't used.
--- @field isHarmful boolean Access to the base flag that determines if this effect is counted as a hostile action.
--- @field lightingBlue number The amount of blue lighting to use when lighting projectiles.
--- @field lightingGreen number The amount of green lighting to use when lighting projectiles.
--- @field lightingRed number The amount of red lighting to use when lighting projectiles.
--- @field name string *Read-only*. Player-facing name of the effect.
--- @field nonRecastable boolean Access to the base flag that determines if this effect can be refreshed by recasting.
--- @field particleTexture boolean *Read-only*. The path to use for the particle effect texture.
--- @field school number The school that the effect is associated with. Maps to [`tes3.magicSchool`](https://mwse.github.io/MWSE/references/magic-schools/) constants.
--- @field size number The size scale for the spells containing this magic effect.
--- @field sizeCap number The maximum possible size of the spell projectile with this effect.
--- @field skill number *Read-only*. The skill for the associated school that the effect is associated with.
--- @field speed number No description yet available.
--- @field spellFailureSoundEffect tes3sound The sound effect that plays when a spell fails to cast, and when magic is resisted. This is determined only by the spell school.
--- @field targetsAttributes boolean Access to the base flag that determines if this effect makes use of attributes.
--- @field targetsSkills boolean Access to the base flag that determines if this effect makes use of skills.
--- @field unreflectable boolean Access to the base flag that determines if this effect can't be reflected.
--- @field usesNegativeLighting boolean Access to the base flag that determines if this effect provides negative lighting.
tes3magicEffect = {}

