-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- An attachment-capable structure to manage a travel destination. This is either exposed as a destination attachment for a door or as part of a list of possible travel services in an actor's AI configuration.
--- @class tes3travelDestinationNode
--- @field cell tes3cell The destination cell.
--- @field marker tes3reference The reference door marker that the destination places the traveling actor at.
tes3travelDestinationNode = {}

