return {
	["root"] = 0,
	["head"] = 1,
	["neck"] = 2,
	["spine"] = 3,
	["pelvis"] = 4,
	["rightHand"] = 5,
	["leftHand"] = 6,
	["rightForearm1"] = 7,
	["leftForearm1"] = 8,
	["rightForearm2"] = 9,
	["leftForearm2"] = 10,
	["rightUpperArm"] = 11,
	["leftUpperArm"] = 12,
	["rightFoot"] = 13,
	["leftFoot"] = 14,
	["rightCalf1"] = 15,
	["leftCalf1"] = 16,
	["rightCalf2"] = 17,
	["leftCalf2"] = 18,
	["rightThigh"] = 19,
	["leftThigh"] = 20,
	["rightClavicle"] = 21,
	["leftClavicle"] = 22,
	["weapon"] = 23,
	["shield"] = 24,
}