return {
	["head"] = 0,
	["hair"] = 1,
	["neck"] = 2,
	["chest"] = 3,
	["groin"] = 4,
	["hand"] = 5,
	["wrist"] = 6,
	["forearm"] = 7,
	["upperArm"] = 8,
	["foot"] = 9,
	["ankle"] = 10,
	["knee"] = 11,
	["upperLeg"] = 12,
	["clavicle"] = 13,
	["tail"] = 14,
}