return {
	button = "button",
	fillbar = "fillbar",
	image = "image",
	layout = "layout",
	luaWidget = "luaWidget",
	model = "model",
	paragraphInput = "paragraphInput",
	rect = "rect",
	scrollBar = "scrollBar",
	scrollPane = "scrollPane",
	text = "text",
	textInput = "textInput",
	textSelect = "textSelect",
}
