return {
	mouseLeave = "mouseLeave",
	mouseOver = "mouseOver",
	mouseDown = "mouseDown",
	mouseClick = "mouseClick",
	mouseScrollUp = "mouseScrollUp",
	mouseScrollDown = "mouseScrollDown",
	mouseDoubleClick = "mouseDoubleClick",
	mouseStillIdle = "mouseStillIdle",
	mouseStillOver = "mouseStillOver",
	mouseStillPressed = "mouseStillPressed",
	mouseStillPressedOutside = "mouseStillPressedOutside",
	mouseRelease = "mouseRelease",
	keyPress = "keyPress",
	keyEnter = "keyEnter",
	help = "help",
	focus = "focus",
	unfocus = "unfocus",
	preUpdate = "preUpdate",
	update = "update",
	destroy = "destroy",
	partScrollBarChanged = "PartScrollBar_changed",
}
