return {
	type = "function",
	description = [[Creates a new 4 by 4 matrix from 4 provided vectors or 16 numbers. Creates an empty matrix if nothing is provided.]],
	arguments = {
		{ name = "w0", type = "number", optional = true, default = 0 },
		{ name = "x0", type = "number", optional = true, default = 0 },
		{ name = "y0", type = "number", optional = true, default = 0 },
		{ name = "z0", type = "number", optional = true, default = 0 },
		{ name = "w1", type = "number", optional = true, default = 0 },
		{ name = "x1", type = "number", optional = true, default = 0 },
		{ name = "y1", type = "number", optional = true, default = 0 },
		{ name = "z1", type = "number", optional = true, default = 0 },
		{ name = "w2", type = "number", optional = true, default = 0 },
		{ name = "x2", type = "number", optional = true, default = 0 },
		{ name = "y2", type = "number", optional = true, default = 0 },
		{ name = "z2", type = "number", optional = true, default = 0 },
		{ name = "w3", type = "number", optional = true, default = 0 },
		{ name = "x3", type = "number", optional = true, default = 0 },
		{ name = "y3", type = "number", optional = true, default = 0 },
		{ name = "z3", type = "number", optional = true, default = 0 },
		{ name = "w", type = "tes3vector4", optional = true },
		{ name = "x", type = "tes3vector4", optional = true },
		{ name = "y", type = "tes3vector4", optional = true },
		{ name = "z", type = "tes3vector4", optional = true },
	},
	returns = {{ name = "matrix", type = "tes3matrix44" }},
}