-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- Access to MGE's macro functions.
--- @class mge.macroslib
mge.macros = {}

--- Triggers the MGE "Decrease FOV" macro.
function mge.macros.decreaseFOV() end

--- Triggers the MGE "Decrease View Range" macro.
function mge.macros.decreaseViewRange() end

--- Triggers the MGE "Decrease Zoom" macro.
function mge.macros.decreaseZoom() end

--- Triggers the MGE "Disable Music" macro.
function mge.macros.disableMusic() end

--- Triggers the MGE "Haggle Less 1" macro.
function mge.macros.haggleLess1() end

--- Triggers the MGE "Haggle Less 10" macro.
function mge.macros.haggleLess10() end

--- Triggers the MGE "Haggle Less 100" macro.
function mge.macros.haggleLess100() end

--- Triggers the MGE "Haggle Less 1,000" macro.
function mge.macros.haggleLess1000() end

--- Triggers the MGE "Haggle Less 10,000" macro.
function mge.macros.haggleLess10000() end

--- Triggers the MGE "Haggle More 1" macro.
function mge.macros.haggleMore1() end

--- Triggers the MGE "Haggle More 10" macro.
function mge.macros.haggleMore10() end

--- Triggers the MGE "Haggle More 100" macro.
function mge.macros.haggleMore100() end

--- Triggers the MGE "Haggle More 1,000" macro.
function mge.macros.haggleMore1000() end

--- Triggers the MGE "Haggle More 10,000" macro.
function mge.macros.haggleMore10000() end

--- Triggers the MGE "Increase FOV" macro.
function mge.macros.increaseFOV() end

--- Triggers the MGE "Increase View Range" macro.
function mge.macros.increaseViewRange() end

--- Triggers the MGE "Increase Zoom" macro.
function mge.macros.increaseZoom() end

--- Triggers the MGE "Move Back 3rd Person Camera" macro.
function mge.macros.moveBack3PCam() end

--- Triggers the MGE "Move Down 3rd Person Camera" macro.
function mge.macros.moveDown3PCam() end

--- Triggers the MGE "Move Forward 3rd Person Camera" macro.
function mge.macros.moveForward3PCam() end

--- Triggers the MGE "Move Left 3rd Person Camera" macro.
function mge.macros.moveLeft3PCam() end

--- Triggers the MGE "Move Right 3rd Person Camera" macro.
function mge.macros.moveRight3PCam() end

--- Triggers the MGE "Move Up 3rd Person Camera" macro.
function mge.macros.moveUp3PCam() end

--- Triggers the MGE "Next Track" macro.
function mge.macros.nextTrack() end

--- Triggers the MGE "Reset Enable Zoom" macro.
function mge.macros.resetEnableZoom() end

--- Triggers the MGE "Show Last Message" macro.
function mge.macros.showLastMessage() end

--- Triggers the MGE "Take Screenshot" macro.
function mge.macros.takeScreenshot() end

--- Triggers the MGE "Toggle Blending" macro.
function mge.macros.toggleBlending() end

--- Triggers the MGE "Toggle Crosshair" macro.
function mge.macros.toggleCrosshair() end

--- Triggers the MGE "Toggle Distant Land" macro.
function mge.macros.toggleDistantLand() end

--- Triggers the MGE "Toggle FPS Counter" macro.
function mge.macros.toggleFpsCounter() end

--- Triggers the MGE "Toggle Grass" macro.
function mge.macros.toggleGrass() end

--- Triggers the MGE "Toggle Lighting Mode" macro.
function mge.macros.toggleLightingMode() end

--- Triggers the MGE "Toggle Shaders" macro.
function mge.macros.toggleShaders() end

--- Triggers the MGE "Toggle Shadows" macro.
function mge.macros.toggleShadows() end

--- Triggers the MGE "Toggle Status Text" macro.
function mge.macros.toggleStatusText() end

--- Triggers the MGE "Toggle Transparency AA" macro.
function mge.macros.toggleTransparencyAA() end

--- Triggers the MGE "Toggle Zoom" macro.
function mge.macros.toggleZoom() end

